# Generated by Django 4.2.2 on 2025-03-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, verbose_name="заголовок")),
                ("description", models.TextField(verbose_name="содержимое")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="blog/photo", verbose_name="Превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="признак публикации")),
                ("views_counter", models.PositiveIntegerField(default=0, verbose_name="количество просмотров")),
            ],
        ),
    ]
