# Generated by Django 4.2.2 on 2025-03-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="наименование категории")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание категории")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="NewModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, verbose_name="заголовок")),
                ("description", models.TextField(verbose_name="содержимое")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="newmodel/photo", verbose_name="Превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="признак публикации")),
                ("views_counter", models.PositiveIntegerField(default=0, verbose_name="количество просмотров")),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="наименование продукта")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание продукта")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="product/photo", verbose_name="Фото продукта"),
                ),
                ("price", models.IntegerField(verbose_name="цена за покупку")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="дата создания")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="дата последнего изменения"),
                ),
                ("views_counter", models.PositiveIntegerField(default=0, verbose_name="количество просмотров")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["category", "name"],
            },
        ),
    ]
